apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    uid: P1809F7CD0C757291
    access: proxy
    url: http://influxdb:8086
    isDefault: true
    jsonData:
      version: Flux
      organization: iot_org
      defaultBucket: iot_bucket
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-auth-token
